version: '3.2'
services:
    # db:
    #   image: mongo:3.2
    #   volumes:
    #     - ./datastore/db:/data/db
    #     - ./datastore/configdb:/data/congifdb
    webapp:
      build: .
      command: python3 -u app.py
      ports:
        - "5000:5000"
      volumes:
        - .:/app