version: '3'
services:
  web:
    build: ./p_0/backend
    ports:
      - "8000:8000"
    volumes:
      - ./sos:/app/sos
  mongo:
    image: "mongo:3.6.8-stretch"
    volumes:
      - ./mongo:/data/db
  mongo-express:
    depends_on:
      - "mongo"
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=puyo
      - ME_CONFIG_BASICAUTH_PASSWORD=tetris
  redis:
    image: redis:4-alpine
    ports:
      - '8879:8879'
  worker:
    build:
      context: ./p_2/worker
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
      - SOS_HOST=web
      - SOS_PORT=8000
  queue-wrapper:
    build:
      context: ./p_2/queue-wrapper
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
      - SOS_HOST=web
      - SOS_PORT=8000
    
    ports:
      - '5000:5000'
  front:
    build: ./front-end
    ports:
        - "9000:9000"
    environment:
      - C_HOST=queue-wrapper
      - C_PORT=5000
      - SOS_HOST=web
      - SOS_PORT=8000
