#!/usr/bin/env python3

from moviepy.editor import *
from sys import argv

def make_gif(in_file, out_file, text):
    clip = (VideoFileClip(in_file))
    length_clip = clip.duration
    start = (2*clip.duration)/3
    end = start + 5
    

    clip = clip.subclip(start, end).resize((320,240))
    if text ==  "":
        clip.write_gif(out_file, fps=10, fuzz=2)
        return

    text = (TextClip(text,method="label",
                   fontsize=30, color='white',
                   font='Impact', interline=-25,
                   stroke_color='black', stroke_width=1.5)
           .set_pos(("center","bottom"))
           .set_duration(clip.duration))

    composition = CompositeVideoClip( [clip, text] )
    composition.write_gif(out_file, fps=10, fuzz=2)

if __name__=='__main__':
    arg1 = argv[1]
    arg2 = argv[2]
    if len(argv) == 4:
        arg3 = argv[3]
    else:
        arg3 = ""
    make_gif(arg1, arg2, arg3)

